/*****************************************************************************
* 
* NXP Confidential Proprietary
*
* Copyright (c) 2014-2016 Freescale Semiconductor
* Copyright 2017 NXP 
* All Rights Reserved
*
******************************************************************************
*
* THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
* IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
* IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGE.
*
****************************************************************************/

#ifndef APEXCVERRORCODES_HPP
#define APEXCVERRORCODES_HPP

#include <stdint.h>
typedef uint32_t APEXCV_LIB_RESULT;

// Success has to be zero
#define APEXCV_SUCCESS                               0x00U

// Unspecified error has occurred - signal all bits
#define APEXCV_ERROR_FAILURE                         0xFFFFFFFFU

// Low 16 bits Host Error
#define APEXCV_ERROR_INTERNAL_ERROR                  0x0001U
#define APEXCV_ERROR_OBJECT_ISNOT_INITIALIZED        0x0002U
#define APEXCV_ERROR_OBJECT_ALREADY_INITIALIZED      0x0004U
#define APEXCV_ERROR_MEMORY_ALLOCATION_FAILED        0x0008U
#define APEXCV_ERROR_INVALID_ARGUMENT                0x0010U

// High 16 bits ACF returned error
#define APEXCV_ERROR_ACF_PROC_SETROI                 0x00010000U
#define APEXCV_ERROR_ACF_PROC_INITIALIZE             0x00020000U
#define APEXCV_ERROR_ACF_PROC_SELECTAPUCONFIG        0x00040000U
#define APEXCV_ERROR_ACF_PROC_CONNECTIO              0x00080000U
#define APEXCV_ERROR_ACF_PROC_OVERRIDEPORTCHUNKSIZE  0x00100000U
#define APEXCV_ERROR_ACF_PROC_QUERYPORTCHUNKSIZE     0x00200000U
#define APEXCV_ERROR_ACF_PROC_SELECTSCENARIO         0x00400000U
#define APEXCV_ERROR_ACF_PROC_EXEC                   0x00800000U

#endif /* APEXCVERRORCODES_HPP */
